### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CyberKiller40** [ianiD/lua_gamejolt_api#2]
What is the license of the code? Will it be GPLv3 compatible?

**Comment by ianiD** [comment]
Yeah, sure. As long as you don't claim you made it or stuff like that, I'm okay with it ;)

**Comment by CyberKiller40** [comment]
OK, but what is the license? I try to be legally clear with my works, so it would be nice if your code had something, anything attached. If you want only crediting then MIT or zlib licenses should be ok for you, but it needs to be actually specified somewhere.

I'm still several months before I'll be integrating GJ with my game, so you take your time, think about this, etc.

**Comment by ianiD** [comment]
Well, Zlib it is, then.
